name: tvSink
description: A new Flutter project.

version: 1.0.15+15

environment:
  sdk: ">=2.16.0-134.5.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.5.0
  scrollable_positioned_list: ^0.2.3
  cached_network_image: ^3.2.0
  transparent_image: ^2.0.0
  package_info_plus: ^4.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.2+1
  share_plus: ^10.0.3
  google_mobile_ads: ^1.2.0
  connectivity_plus: ^5.0.2
  fijkplayer: ^0.11.0
  flutter_easyloading: ^3.0.5
  parse_server_sdk_flutter: ^8.0.0
  logger: ^1.1.0
  retry: ^3.1.2
  supabase_flutter: ^2.8.0
  open_file: ^3.2.1
  dio: ^5.7.0
  shared_preferences: ^2.0.13
  #状态管理
  provider: ^6.0.1
  # 消息中心（事件发送和监听）
  event_bus: ^2.0.0
  permission_handler: 11.3.1
  url_launcher: ^6.3.1
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_native_splash:
  branding: "images/splash_icon.png"
  color: "#ffffff"
  branding_mode: bottom
#  background_image : "images/startup.png"
  ardroid: true
  ios: true